.TH paraminspector 1 "2010-07-06" "tuchulcha 0.2.1" "Heidelberg Collaboratory for Image Processing"
.SH NAME
Tuchulcha - A graphical configuration tool for charon
.SH SYNOPSIS
\fBparaminspector\fR
.SH DESCRIPTION
\fBparaminspector\fR is a simple editor for parameter files.
Files have to be opened from within the running application.
No options from the command line are currently used.

\fBparaminspector\fR is a standalone version of the object inspector
used as widget in \fBtuchulcha\fR.
