.TH templategenerator 1 "2011-05-05" "templategenerator 0.1.3" "Heidelberg Collaboratory for Image Processing"
.SH NAME
Charon Templategenerator - A Qt Wizard for charon module code template generation
.SH SYNOPSIS
\fBtemplategenerator\fR
.SH DESCRIPTION
.B templategenerator
opens a self-explaining wizard application for charon module code template generation.
The generated module templates will be saved to the location shown in the summary wizard page.
