.TH tuchulcha 1 "2010-07-06" "tuchulcha 0.2.1" "Heidelberg Collaboratory for Image Processing"
.SH NAME
Tuchulcha - A graphical configuration tool for charon
.SH SYNOPSIS
\fBtuchulcha\fR [\fIworkflowfile\fR]
.SH DESCRIPTION
.B tuchulcha
opens the given workflow or starts with an empty workspace.
.SH FILES
.TP
\fIworflowfile\fB
Parameter file describing the workflow to be configured
or executed. If no workflow file is given, tuchulcha starts
with an empty workspace.
