/*  Copyright (C) 2012 Gerald Mwangi

	This file is part of Charon.

	Charon is free software: you can redistribute it and/or modify
	it under the terms of the GNU Lesser General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	Charon is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU Lesser General Public License for more details.

	You should have received a copy of the GNU Lesser General Public License
	along with Charon.  If not, see <http://www.gnu.org/licenses/>.
*/
/** \file VirtualSlotTestReader.h
 *  \author <a href="mailto:gerald.mwangi@gmx.de">
 *      Gerald Mwangi</a>
 *  \date 28.11.2012
 *  Declaraion of parameter class VirtualSlotTestReader.
 */
#ifndef _VIRTUALSLOTTESTREADER_H_
#define _VIRTUALSLOTTESTREADER_H_

#ifdef _MSC_VER
#ifdef virtualslottestreader_EXPORTS
/// Visual C++ specific code
#define virtualslottestreader_DECLDIR __declspec(dllexport)
#else
#define virtualslottestreader_DECLDIR __declspec(dllimport)
#endif /*Export or import*/
#else
/// Not needed without MSVC
#define virtualslottestreader_DECLDIR
#endif

#include <charon-core/ParameteredObject.h>


/// Tests if the data passed to its input matches the data generated by
/// VirtualSlotTestWriter
/** Tests if the data passed to its input matches the data generated by
 *  VirtualSlotTestWriter
 */
class virtualslottestreader_DECLDIR VirtualSlotTestReader : public ParameteredObject {
public:
	/// default constructor
	/// \param name             instance name
	VirtualSlotTestReader(const std::string& name = "");

	/// integer
	InputSlot< int > integer;
	/// image
	InputSlot< std::vector<double> > image;


protected:
	/// Update object.
	virtual void execute();
};

#endif /* _VIRTUALSLOTTESTREADER_H_ */
