# - Find petsc
#
# Usage:
#  FIND_PACKAGE(petsc[ REQUIRED][ QUIET])
#  INCLUDE_DIRECTORIES(${PETSC_INCLUDE_DIRS})
#  ADD_EXECUTABLE(bla main.cpp)
#  TARGET_LINK_LIBRARIES(bla petsc)
#
# This sets the variables:
#  PETSC_ROOT_DIR 		     petsc installation directory
#  PETSC_INCLUDE_DIRS        petsc include directory

# search for header files
FIND_PATH(PETSC_ROOT_DIR
    NAMES           include/petscksp.h
    PATHS           /usr
                    /usr/local
                    /opt
    DOC             "petsc root directory"
)

# as multiple compiled version of petsc with different architectures
# can reside in the root directory, the architecture has to be specified
# manually using PETSC_ARCH
# with both the ROOT_DIR and ARCH every needed path can be generated
SET(PETSC_ARCH win_x86_32_mpiuni CACHE STRING "selecte petsc architecture")
OPTION(WITH_MPI "does PETSc use an external MPI implementation?" OFF)
OPTION(WITH_FORTRAN "was fortran used for PETSc-compilation?" OFF)

SET(PETSC_LIBRARY_SEARCH_PATHS
	${PETSC_ROOT_DIR}/lib/${PETSC_ARCH}
	/etc/alternatives
)

FIND_LIBRARY(PETSC_LIBPETSC petsc
	HINTS ${PETSC_LIBRARY_SEARCH_PATHS}
)
FIND_LIBRARY(PETSC_LIBPETSCCONTRIB petsccontrib
	HINTS ${PETSC_LIBRARY_SEARCH_PATHS}
)
FIND_LIBRARY(PETSC_LIBPETSCDM petscdm
	HINTS ${PETSC_LIBRARY_SEARCH_PATHS}
)
FIND_LIBRARY(PETSC_LIBPETSCKSP petscksp
	HINTS ${PETSC_LIBRARY_SEARCH_PATHS}
)
FIND_LIBRARY(PETSC_LIBPETSCMAT petscmat
	HINTS ${PETSC_LIBRARY_SEARCH_PATHS}
)
FIND_LIBRARY(PETSC_LIBPETSCSNES petscsnes
	HINTS ${PETSC_LIBRARY_SEARCH_PATHS}
)
FIND_LIBRARY(PETSC_LIBPETSCTS petscts
	HINTS ${PETSC_LIBRARY_SEARCH_PATHS}
)
FIND_LIBRARY(PETSC_LIBPETSCVEC petscvec
	HINTS ${PETSC_LIBRARY_SEARCH_PATHS}
)

SET(PETSC_LIBVARS
	PETSC_LIBPETSC
	PETSC_LIBPETSCCONTRIB
	PETSC_LIBPETSCDM
	PETSC_LIBPETSCKSP
	PETSC_LIBPETSCMAT
	PETSC_LIBPETSCSNES
	PETSC_LIBPETSCTS
	PETSC_LIBPETSCVEC
)
SET(PETSC_LIBRARIES)

#add blas/lapack of petsc
IF (WITH_FORTRAN)
	FIND_LIBRARY(PETSC_LIBFLAPACK
		NAMES 	flapack lapackgf lapackgf-3
		HINTS 	${PETSC_LIBRARY_SEARCH_PATHS}
				${PETSC_ROOT_DIR}/externalpackages/fblaslapack/${PETSC_ARCH}
	)
	LIST(APPEND PETSC_LIBVARS
		PETSC_LIBFLAPACK
	)
ELSE (WITH_FORTRAN)
	FIND_LIBRARY(PETSC_LIBF2CBLAS f2cblas
		HINTS	${PETSC_LIBRARY_SEARCH_PATHS}
				${PETSC_ROOT_DIR}/externalpackages/f2cblaslapack/${PETSC_ARCH}
	)
	FIND_LIBRARY(PETSC_LIBF2CLAPACK f2clapack
		HINTS	${PETSC_LIBRARY_SEARCH_PATHS}
				${PETSC_ROOT_DIR}/externalpackages/f2cblaslapack/${PETSC_ARCH}
	)
	LIST(APPEND PETSC_LIBVARS
		PETSC_LIBF2CBLAS
		PETSC_LIBF2CLAPACK
	)
ENDIF (WITH_FORTRAN)

#add MPI support
IF (WITH_MPI)
	FIND_PACKAGE(MPI REQUIRED)
	LIST(APPEND PETSC_LIBRARIES
		${MPI_LIBRARIES}
	)
ELSE (WITH_MPI)
	FIND_LIBRARY(PETSC_LIBMPIUNI
		NAMES mpiuni
		HINTS ${PETSC_LIBRARY_SEARCH_PATHS}
	)
	LIST(APPEND PETSC_LIBVARS
		PETSC_LIBMPIUNI
	)
ENDIF (WITH_MPI)

SET(PETSC_INCLUDE_DIRS
	${PETSC_ROOT_DIR}/include/
	${PETSC_ROOT_DIR}/bmake/${PETSC_ARCH}/
)
IF (WITH_MPI)
	LIST(APPEND PETSC_INCLUDE_DIRS
		${MPI_INCLUDE_PATH}
	)
ELSE (WITH_MPI)
	LIST(APPEND PETSC_INCLUDE_DIRS
		${PETSC_ROOT_DIR}/include/mpiuni/
	)		
ENDIF (WITH_MPI)

# check if everything went fine
INCLUDE(FindPackageHandleStandardArgs)
IF(NOT PETSC_ROOT_DIR)
	MESSAGE(SEND_ERROR
		"PETSc has not been found. "
		"Please set PETSC_ROOT_DIR to the directory, "
		"where you have installed PETSc. "
	)
ENDIF(NOT PETSC_ROOT_DIR)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(petsc DEFAULT_MSG
    PETSC_ROOT_DIR
	${PETSC_LIBVARS}
)

FOREACH(LIB ${PETSC_LIBVARS})
	LIST(APPEND PETSC_LIBRARIES
		${LIB}
	)
ENDFOREACH(LIB ${PETSC_LIBVARS})

MARK_AS_ADVANCED(
    PETSC_ROOT_DIR
	PETSC_ARCH
    PETSC_CONFIG_DIR
	${PETSC_LIBVARS}
)

IF(COMMAND UNSET)
	UNSET(PETSC_LIBVARS)
ENDIF(COMMAND UNSET)
