FILE(READ ${PROJECT_SOURCE_DIR}/include/${PROJECT_NAME}/configVersion.h VERSION_FILE)
STRING(TOUPPER ${PROJECT_NAME} _UPROJNAME)
STRING(REPLACE - _ _UPROJNAME ${_UPROJNAME})
STRING(REGEX MATCH "${_UPROJNAME}_VERSION_MAJOR[ \t\n]+([^ \t\n]+)" _TMP_VAR ${VERSION_FILE})
SET(${PROJECT_NAME}_VERSION_MAJOR ${CMAKE_MATCH_1})
STRING(REGEX MATCH "${_UPROJNAME}_VERSION_MINOR[ \t\n]+([^ \t\n]+)" _TMP_VAR ${VERSION_FILE})
SET(${PROJECT_NAME}_VERSION_MINOR ${CMAKE_MATCH_1})
STRING(REGEX MATCH "${_UPROJNAME}_VERSION_PATCH[ \t\n]+([^ \t\n]+)" _TMP_VAR ${VERSION_FILE})
SET(${PROJECT_NAME}_VERSION_PATCH ${CMAKE_MATCH_1})
UNSET(_TMP_VAR)
UNSET(_UPROJNAME)
UNSET(VERSION_FILE)

SET(${PROJECT_NAME}_VERSION_SHORT
	${${PROJECT_NAME}_VERSION_MAJOR}.${${PROJECT_NAME}_VERSION_MINOR})
SET(${PROJECT_NAME}_VERSION
	${${PROJECT_NAME}_VERSION_MAJOR}.${${PROJECT_NAME}_VERSION_MINOR}.${${PROJECT_NAME}_VERSION_PATCH})
